"""LensRuntime: Bootstrap context for cn-lens CLI invocations.

Reuses utils.config.read_config and utils.logging.ThreadSafeFileHandler from
the same helpers as main.py so that cn-lens shares config and log plumbing
with the menu-driven cn-tool without duplicating any of that logic.

In --offline mode (or when config_paths is empty/absent) no auth is attempted,
cache is skipped, and credentials remain blank on the context.  This keeps
unit tests deterministic and config-free.

No print / console output from this module — logger only.
"""
from __future__ import annotations

import logging
import threading
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Tuple

from core.base import ScriptContext
from core.event_bus import EventBus
from core.loader import collect_plugin_schemas
from utils.auth import ensure_infoblox_auth, ensure_device_auth
from utils.config import BASE_CONFIG_SCHEMA, normalize_runtime_flags, read_config
from utils.logging import ThreadSafeFileHandler
from utils.stats import StatsManager


# ---------------------------------------------------------------------------
# Auth scope dispatch map
# ---------------------------------------------------------------------------

def _ensure_infoblox_credentials(ctx: "ScriptContext") -> Tuple[str, str]:
    """Delegate to ensure_infoblox_auth (also wires HTTP session)."""
    return ensure_infoblox_auth(ctx)


def _ensure_ad_credentials(ctx: "ScriptContext") -> Tuple[str, str]:
    """Delegate to ensure_device_auth (TACACS/GPG path, no HTTP session)."""
    return ensure_device_auth(ctx)


#: Dispatch map from scope name → credential-acquire function.
#: Add a new entry here when a new adapter scope is introduced.
_SCOPE_HANDLERS: Dict[str, Callable[["ScriptContext"], Tuple[str, str]]] = {
    "infoblox": _ensure_infoblox_credentials,
    "ad": _ensure_ad_credentials,
    # "device" scope: same TACACS/GPG credential path as "ad"; no HTTP session
    # wiring is needed for SSH connections handled by netmiko.
    "device": _ensure_ad_credentials,
}


# ---------------------------------------------------------------------------
# Public dataclass: LensOptions
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class LensOptions:
    """Immutable options derived from CLI arguments and passed into LensRuntime."""

    offline: bool
    """Skip all live adapters, auth, and network bootstrap."""

    run_id: Optional[str]
    """Explicit run ID; None → auto-generated by workflow."""


# ---------------------------------------------------------------------------
# LensRuntime
# ---------------------------------------------------------------------------

class LensRuntime:
    """Shared runtime context for all cn-lens workflows.

    Attributes
    ----------
    options : LensOptions
        Immutable options derived from CLI arguments.
    logger : logging.Logger
        Namespaced 'cn_lens' logger (file-backed or NullHandler in tests).
    cfg : Dict[str, Any]
        Merged configuration dict from all config paths.
    context : ScriptContext
        The shared context object (same type used by menu modules).
    cache : CacheManager or None
        CacheManager instance when ``cache_enabled`` is set in the merged
        config; ``None`` otherwise (config_repo falls back to live scan).
    """

    def __init__(
        self,
        options: LensOptions,
        logger: logging.Logger,
        cfg: Dict[str, Any],
        context: ScriptContext,
        cache: Any = None,
        stats: Optional["StatsManager"] = None,
    ) -> None:
        self.options = options
        self.logger = logger
        self.cfg = cfg
        self.context = context
        self.cache = cache  # CacheManager or None (built by build_runtime)
        #: StatsManager instance, or None when stats collection is not enabled.
        #: Populated by build_runtime when stats_collect_enabled or stats_menu_enabled
        #: is True in the merged config.  Mirrors the stats_support plugin's
        #: semantics exactly (privacy-by-design, per-user sharded JSON.gz files).
        self.stats: Optional[StatsManager] = stats
        #: Per-scope set of scopes whose side-effects have already been executed.
        #: Credentials themselves may be shared across scopes (same TACACS user),
        #: but each scope's side-effects (e.g. HTTP session wiring for "infoblox")
        #: must run exactly once regardless of whether another scope ran first.
        self._ensured_scopes: set[str] = set()
        #: RLock that serialises concurrent ensure_credentials calls from
        #: ThreadPoolExecutor workers (e.g. collect_many).  Re-entrant so that
        #: a single-thread caller can acquire without deadlocking.
        self._cred_lock: threading.RLock = threading.RLock()
        #: Memoised SD-WAN YAML store (file_path → parsed content).
        #: Populated on first call to any sdwan_yaml adapter function that
        #: needs file data; cleared by the REPL ``reload`` command so the
        #: next lookup re-parses from disk.  ``None`` means not yet loaded.
        self._sdwan_store: "dict | None" = None

    @property
    def offline(self) -> bool:
        return self.options.offline

    def as_offline(self) -> "LensRuntime":
        """Return a new ``LensRuntime`` identical to *self* but with ``offline=True``.

        All fields (logger, cfg, context, cache, _ensured_scopes) are shared by
        reference with the original runtime — the only difference is that
        ``options`` is replaced with a copy that has ``offline=True``.

        This is the canonical way for the REPL's ``doctor --offline`` path to
        create a transient offline twin without re-wrapping by hand (which would
        silently drop any new fields added in the future).
        """
        import dataclasses as _dc  # noqa: PLC0415
        offline_options = _dc.replace(self.options, offline=True)
        twin = LensRuntime(
            options=offline_options,
            logger=self.logger,
            cfg=self.cfg,
            context=self.context,
            cache=self.cache,
            stats=self.stats,
        )
        # Share already-acquired credential scopes so the twin doesn't re-prompt
        # if somehow invoked in a context where credentials were already cached.
        twin._ensured_scopes = self._ensured_scopes
        # Share the same credential lock — offline twins are short-lived but we
        # keep the reference consistent.
        twin._cred_lock = self._cred_lock
        # Share the memoised sdwan store — same config/files, so re-parsing is
        # wasteful.  The offline twin is transient (e.g. doctor --offline) and
        # won't mutate the store, so sharing is safe.  If the user later runs
        # ``reload`` on the original runtime, its _sdwan_store is reset to None;
        # any already-created offline twin keeps the old reference (harmless —
        # offline twins are short-lived and never look up sdwan data anyway).
        twin._sdwan_store = self._sdwan_store
        return twin

    def ensure_credentials(self, scope: str = "infoblox") -> Tuple[str, str]:
        """Lazily ensure live credentials are available on the context.

        In offline mode this raises ``RuntimeError`` immediately — no network
        bootstrap is possible.  In online mode it delegates to the appropriate
        scope handler (``utils.auth.ensure_infoblox_auth`` or
        ``utils.auth.ensure_device_auth``) which reads ``TACACS_PW``/``USER``
        env vars, falls back to GPG, and finally prompts the user.

        Idempotency is per-scope: a second call with the same scope is a no-op.
        A call with a different scope always executes its handler, even when
        credentials are already set on ``self.context`` by a prior scope.  This
        is essential because each scope may have unique side-effects: the
        ``"infoblox"`` scope calls ``install_infoblox_auth`` to wire the shared
        HTTP session, while the ``"ad"`` scope does not — so AD running first
        must not prevent infoblox from setting up session auth (B3).

        Parameters
        ----------
        scope:
            Per-adapter auth scope. Supported values:

            ``"infoblox"`` (default)
                Delegates to ``utils.auth.ensure_infoblox_auth`` which also
                wires up the shared HTTP session.

            ``"ad"``
                Delegates to ``utils.auth.ensure_device_auth`` — same
                TACACS/GPG credential path as infoblox but without touching
                the HTTP session, which is not used by LDAP.

        Returns
        -------
        Tuple[str, str]
            ``(username, password)`` from ``self.context``.

        Raises
        ------
        RuntimeError
            When called in offline mode.
        """
        if self.offline:
            raise RuntimeError(
                "credentials unavailable in offline mode — "
                "re-run without --offline to authenticate"
            )
        with self._cred_lock:
            # Per-scope idempotency: short-circuit only when THIS scope's side-effects
            # have already been executed.  Scopes share credentials (same TACACS/GPG
            # user) but each scope may have unique side-effects — in particular the
            # "infoblox" scope must run install_infoblox_auth to wire the HTTP session
            # even when credentials were already populated by the "ad" scope first.
            if scope in self._ensured_scopes:
                return (self.context.username, self.context.password)
            handler = _SCOPE_HANDLERS.get(scope)
            if handler is None:
                raise ValueError(
                    f"unknown scope {scope!r}; "
                    f"supported: {', '.join(sorted(_SCOPE_HANDLERS))}"
                )
            username, password = handler(self.context)
            # Ensure the context reflects the returned credentials even if the
            # auth helper (or a test mock) did not mutate the context directly.
            if username:
                self.context.username = username
            if password:
                self.context.password = password
            self._ensured_scopes.add(scope)
            return (self.context.username, self.context.password)


# ---------------------------------------------------------------------------
# Factory: build_runtime
# ---------------------------------------------------------------------------

def build_runtime(
    options: LensOptions,
    *,
    config_paths: List[Path] | None = None,
) -> LensRuntime:
    """Build a ``LensRuntime`` from ``LensOptions`` and an optional list of config paths.

    Parameters
    ----------
    options:
        Frozen options derived from CLI args.
    config_paths:
        Ordered list of ``.cn``-style INI files to read (lowest → highest
        priority).  Missing paths are silently ignored — same behaviour as
        ``main.py``.  Pass ``[]`` or ``None`` to use defaults only.

    Returns
    -------
    LensRuntime
        A fully initialised runtime ready for workflow and adapter use.
    """
    # --- Config ---------------------------------------------------------
    # Build cfg first so _build_logger can derive log settings from it
    # without a second configparser read.
    cfg = _build_cfg(config_paths or [], logging.getLogger("cn_lens"))

    # --- Logger ---------------------------------------------------------
    logger = _build_logger(cfg)

    # --- ScriptContext --------------------------------------------------
    # console is typed as ThemedConsole in the original codebase; cn-lens
    # does not use console output from the runtime itself, so we stub it
    # with None.  Adapters that need display formatting import their own
    # console.
    context = ScriptContext(
        cfg=cfg,
        logger=logger,
        console=None,  # type: ignore[arg-type]
        cache=None,
        event_bus=EventBus(),
        username="",
        password="",
        plugins=[],
    )

    # --- Stats -----------------------------------------------------------
    # Mirror stats_support plugin semantics: instantiate StatsManager when any
    # stats flag is enabled.  Privacy model unchanged: per-user sharded JSON.gz
    # files under stats_directory (same as cn-tool).  Reading (stats_menu_enabled)
    # never writes; writing (stats_collect_enabled) records session/run data.
    stats: Optional[StatsManager] = None
    if (
        cfg.get("stats_collect_enabled")
        or cfg.get("stats_menu_enabled")
        or cfg.get("stats_read_shared_on_startup")
    ):
        try:
            stats = StatsManager(context)
        except Exception as exc:
            logger.warning("LensRuntime: could not initialise StatsManager: %s", exc)

    # --- Cache (F3) ---------------------------------------------------------
    # Construct CacheManager when cache_enabled is set in config, mirroring
    # the semantics in core/background.py exactly:
    #   CacheManager.get_instance(directory=ctx.cfg["cache_directory"], logger=..., cfg=...)
    # Skipped in offline mode (per module docstring contract).
    # Failure is non-fatal: a warning is logged and cache remains None
    # (config_repo adapter falls back to live file-system scan;
    # source_status stays "live").
    cache = None
    if not options.offline and cfg.get("cache_enabled"):
        cache_dir = cfg.get("cache_directory")
        if not cache_dir:
            logger.warning(
                "LensRuntime: cache_enabled=True but cache_directory is missing or empty"
                " — cache not initialised"
            )
        else:
            try:
                from utils.cache import CacheManager  # type: ignore[import]
                cache = CacheManager.get_instance(
                    directory=Path(str(cache_dir)).expanduser(),
                    logger=logger,
                    cfg=cfg,
                )
                context.cache = cache
            except Exception as exc:
                logger.warning("LensRuntime: could not initialise CacheManager: %s", exc)

    logger.debug(
        "LensRuntime built (offline=%s, stats=%s, cache=%s)",
        options.offline, stats is not None, cache is not None,
    )
    return LensRuntime(options=options, logger=logger, cfg=cfg, context=context, stats=stats, cache=cache)


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------

def _build_logger(cfg: Dict[str, Any]) -> logging.Logger:
    """Return a 'cn_lens' logger using settings already parsed by read_config.

    Derives ``log_file`` and ``log_level`` from ``cfg["logging_file"]`` /
    ``cfg["logging_level"]`` — the same keys populated by ``BASE_CONFIG_SCHEMA``
    — so there is no second ``configparser`` parse.  Uses
    ``utils.logging.ThreadSafeFileHandler`` (already imported) when a log file
    path is available.  Falls back to ``NullHandler`` so tests never need a
    real log file.
    """
    logger = logging.getLogger("cn_lens")

    if logger.handlers:
        # Already configured (e.g. re-entrant call in tests)
        return logger

    log_file = cfg.get("logging_file")
    log_level_str = cfg.get("logging_level") or "INFO"

    log_level_numeric = getattr(logging, str(log_level_str).upper(), logging.INFO)
    logger.setLevel(log_level_numeric)
    logger.propagate = False

    if log_file:
        log_path = Path(str(log_file)).expanduser()
        try:
            fh = ThreadSafeFileHandler(str(log_path))
            fh.setFormatter(logging.Formatter("%(asctime)s - %(levelname)s - %(message)s"))
            logger.addHandler(fh)
            return logger
        except Exception:
            pass  # fall through to NullHandler

    # Fallback: NullHandler (safe for tests and offline use)
    logger.addHandler(logging.NullHandler())
    return logger


def _build_cfg(config_paths: List[Path], logger: logging.Logger) -> Dict[str, Any]:
    """Read merged config using the same schema and helper as main.py.

    Extends BASE_CONFIG_SCHEMA with plugin-contributed keys via
    ``core.loader.collect_plugin_schemas`` so adapters that rely on plugin
    schemas (sdwan_yaml_search, ad, email, …) read their values from ``.cn``.

    After reading, applies ``normalize_runtime_flags`` so that
    ``infoblox_enabled`` and ``config_repo_enabled`` are properly resolved
    booleans — identical to the normalization that ``main.py`` performs after
    its ``read_config`` call.  This fixes B5 (raw string "false" being truthy)
    and B6 (absent enabled key not auto-detecting an accessible repo).
    """
    schema = collect_plugin_schemas(BASE_CONFIG_SCHEMA)
    cfg = read_config(config_paths, schema, logger)
    normalize_runtime_flags(cfg, logger)
    return cfg


