"""LensRuntime: Bootstrap context for cn-lens CLI invocations.

Reuses utils.config.read_config and utils.logging.ThreadSafeFileHandler from
the same helpers as main.py so that cn-lens shares config and log plumbing
with the menu-driven cn-tool without duplicating any of that logic.

In --offline mode (or when config_paths is empty/absent) no auth is attempted,
cache is skipped, and credentials remain blank on the context.  This keeps
unit tests deterministic and config-free.

No print / console output from this module — logger only.
"""
from __future__ import annotations

import configparser
import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Tuple

from core.base import ScriptContext
from core.event_bus import EventBus
from core.loader import collect_plugin_schemas
from utils.auth import ensure_infoblox_auth, ensure_device_auth
from utils.config import BASE_CONFIG_SCHEMA, read_config
from utils.logging import ThreadSafeFileHandler


# ---------------------------------------------------------------------------
# Auth scope dispatch map
# ---------------------------------------------------------------------------

def _ensure_infoblox_credentials(ctx: "ScriptContext") -> Tuple[str, str]:
    """Delegate to ensure_infoblox_auth (also wires HTTP session)."""
    return ensure_infoblox_auth(ctx)


def _ensure_ad_credentials(ctx: "ScriptContext") -> Tuple[str, str]:
    """Delegate to ensure_device_auth (TACACS/GPG path, no HTTP session)."""
    return ensure_device_auth(ctx)


#: Dispatch map from scope name → credential-acquire function.
#: Add a new entry here when a new adapter scope is introduced.
_SCOPE_HANDLERS: Dict[str, Callable[["ScriptContext"], Tuple[str, str]]] = {
    "infoblox": _ensure_infoblox_credentials,
    "ad": _ensure_ad_credentials,
}


# ---------------------------------------------------------------------------
# Public dataclass: LensOptions
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class LensOptions:
    """Immutable options derived from CLI arguments and passed into LensRuntime."""

    offline: bool
    """Skip all live adapters, auth, and network bootstrap."""

    format: str
    """Default output format (e.g. 'human', 'json', 'yaml', 'md', 'xlsx')."""

    output: Optional[Path]
    """File path for output (None → stdout)."""

    run_id: Optional[str]
    """Explicit run ID; None → auto-generated by workflow."""


# ---------------------------------------------------------------------------
# LensRuntime
# ---------------------------------------------------------------------------

class LensRuntime:
    """Shared runtime context for all cn-lens workflows.

    Attributes
    ----------
    options : LensOptions
        Immutable options derived from CLI arguments.
    logger : logging.Logger
        Namespaced 'cn_lens' logger (file-backed or NullHandler in tests).
    cfg : Dict[str, Any]
        Merged configuration dict from all config paths.
    context : ScriptContext
        The shared context object (same type used by menu modules).
    cache : CacheManager | None
        Populated only in online mode when cache is enabled and accessible.
    """

    def __init__(
        self,
        options: LensOptions,
        logger: logging.Logger,
        cfg: Dict[str, Any],
        context: ScriptContext,
        cache: Any = None,
    ) -> None:
        self.options = options
        self.logger = logger
        self.cfg = cfg
        self.context = context
        self.cache = cache

    @property
    def offline(self) -> bool:
        return self.options.offline

    def ensure_credentials(self, scope: str = "infoblox") -> Tuple[str, str]:
        """Lazily ensure live credentials are available on the context.

        In offline mode this raises ``RuntimeError`` immediately — no network
        bootstrap is possible.  In online mode it delegates to
        ``utils.auth.ensure_infoblox_auth`` (the same helper used by main.py)
        which reads ``TACACS_PW``/``USER`` env vars, falls back to GPG, and
        finally prompts the user.  The call is idempotent: if credentials are
        already populated on ``self.context`` the auth helper short-circuits.

        Parameters
        ----------
        scope:
            Per-adapter auth scope. Supported values:

            ``"infoblox"`` (default)
                Delegates to ``utils.auth.ensure_infoblox_auth`` which also
                wires up the shared HTTP session.

            ``"ad"``
                Delegates to ``utils.auth.ensure_device_auth`` — same
                TACACS/GPG credential path as infoblox but without touching
                the HTTP session, which is not used by LDAP.

        Returns
        -------
        Tuple[str, str]
            ``(username, password)`` from ``self.context``.

        Raises
        ------
        RuntimeError
            When called in offline mode.
        """
        if self.offline:
            raise RuntimeError(
                "credentials unavailable in offline mode — "
                "re-run without --offline to authenticate"
            )
        # Short-circuit if credentials already populated (idempotency).
        if self.context.username and self.context.password:
            return (self.context.username, self.context.password)
        handler = _SCOPE_HANDLERS.get(scope)
        if handler is None:
            raise ValueError(
                f"unknown scope {scope!r}; "
                f"supported: {', '.join(sorted(_SCOPE_HANDLERS))}"
            )
        username, password = handler(self.context)
        # Ensure the context reflects the returned credentials even if the
        # auth helper (or a test mock) did not mutate the context directly.
        if username:
            self.context.username = username
        if password:
            self.context.password = password
        return (self.context.username, self.context.password)


# ---------------------------------------------------------------------------
# Factory: build_runtime
# ---------------------------------------------------------------------------

def build_runtime(
    options: LensOptions,
    *,
    config_paths: List[Path] | None = None,
) -> LensRuntime:
    """Build a ``LensRuntime`` from ``LensOptions`` and an optional list of config paths.

    Parameters
    ----------
    options:
        Frozen options derived from CLI args.
    config_paths:
        Ordered list of ``.cn``-style INI files to read (lowest → highest
        priority).  Missing paths are silently ignored — same behaviour as
        ``main.py``.  Pass ``[]`` or ``None`` to use defaults only.

    Returns
    -------
    LensRuntime
        A fully initialised runtime ready for workflow and adapter use.
    """
    # --- Config ---------------------------------------------------------
    # Build cfg first so _build_logger can derive log settings from it
    # without a second configparser read.
    cfg = _build_cfg(config_paths or [], logging.getLogger("cn_lens"))

    # --- Logger ---------------------------------------------------------
    logger = _build_logger(cfg)

    # --- Cache (online only, graceful fallback) -------------------------
    cache = None
    if not options.offline and cfg.get("cache_enabled", True):
        cache = _try_build_cache(cfg, logger)

    # --- ScriptContext --------------------------------------------------
    # console is typed as ThemedConsole in the original codebase; cn-lens
    # does not use console output from the runtime itself, so we stub it
    # with None.  Adapters that need display formatting import their own
    # console.
    context = ScriptContext(
        cfg=cfg,
        logger=logger,
        console=None,  # type: ignore[arg-type]
        cache=cache,
        event_bus=EventBus(),
        username="",
        password="",
        plugins=[],
    )

    logger.debug("LensRuntime built (offline=%s)", options.offline)
    return LensRuntime(options=options, logger=logger, cfg=cfg, context=context, cache=cache)


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------

def _build_logger(cfg: Dict[str, Any]) -> logging.Logger:
    """Return a 'cn_lens' logger using settings already parsed by read_config.

    Derives ``log_file`` and ``log_level`` from ``cfg["logging_file"]`` /
    ``cfg["logging_level"]`` — the same keys populated by ``BASE_CONFIG_SCHEMA``
    — so there is no second ``configparser`` parse.  Uses
    ``utils.logging.ThreadSafeFileHandler`` (already imported) when a log file
    path is available.  Falls back to ``NullHandler`` so tests never need a
    real log file.
    """
    logger = logging.getLogger("cn_lens")

    if logger.handlers:
        # Already configured (e.g. re-entrant call in tests)
        return logger

    log_file = cfg.get("logging_file")
    log_level_str = cfg.get("logging_level") or "INFO"

    log_level_numeric = getattr(logging, str(log_level_str).upper(), logging.INFO)
    logger.setLevel(log_level_numeric)
    logger.propagate = False

    if log_file:
        log_path = Path(str(log_file)).expanduser()
        try:
            fh = ThreadSafeFileHandler(str(log_path))
            fh.setFormatter(logging.Formatter("%(asctime)s - %(levelname)s - %(message)s"))
            logger.addHandler(fh)
            return logger
        except Exception:
            pass  # fall through to NullHandler

    # Fallback: NullHandler (safe for tests and offline use)
    logger.addHandler(logging.NullHandler())
    return logger


def _build_cfg(config_paths: List[Path], logger: logging.Logger) -> Dict[str, Any]:
    """Read merged config using the same schema and helper as main.py.

    Extends BASE_CONFIG_SCHEMA with plugin-contributed keys via
    ``core.loader.collect_plugin_schemas`` so adapters that rely on plugin
    schemas (sdwan_yaml_search, ad, email, …) read their values from ``.cn``.
    """
    schema = collect_plugin_schemas(BASE_CONFIG_SCHEMA)
    return read_config(config_paths, schema, logger)


def _try_build_cache(cfg: Dict[str, Any], logger: logging.Logger) -> Any:
    """Attempt to initialise CacheManager; return None on any failure.

    CacheManager is a singleton in the cn-tool codebase.  In cn-lens the
    runtime is built once per invocation, so we call get_instance() to
    retrieve or create the singleton safely.
    """
    try:
        from utils.cache import CacheManager

        cache_dir = cfg.get("cache_directory")
        if not cache_dir:
            logger.debug("LensRuntime: cache_directory not set, skipping cache init")
            return None

        cache_dir_path = Path(cache_dir).expanduser() if isinstance(cache_dir, str) else Path(cache_dir)
        cache_dir_path.mkdir(parents=True, exist_ok=True)

        return CacheManager.get_instance(
            directory=cache_dir_path,
            logger=logger,
            cfg=cfg,
        )
    except Exception as exc:
        logger.debug("LensRuntime: cache init skipped: %s", exc)
        return None
