from typing import Dict, Tuple

stop_words: Dict[str, Tuple[str, ...]] = {
    "bluecoat": (
        '"',
        "!",
        "max-bandwidth",
        "exit",
        "priority",
        "disable",
        "interface",
        "reject",
        "failover",
        "clear",
        "ssl",
        "inline",
        "-",
        "*",
        "ssh",
        "security hashed-",
        "security windows",
        "group-cache",
        "security radius",
        "alternate-server encrypted-secret",
        "archive-configuration encrypted-",
        "security sequence",
        "security management",
        "access-log",
        "overflow-policy",
        "type",
        "no ",
        "format-name",
        "ftp-client",
        "scp-client",
        "edit log",
        "create log",
        "continuous-upload",
        "upload-settings",
        "service-info",
        "diagnostics",
        "caching",
        "max-cache-size",
        "tunnel",
        "adn",
        "cifs",
        "remote-storage-",
        "mapi",
        "keep-alive",
        "forwarding",
        "load-balance",
        "host-affinity",
        "failure-mode",
        "content-filter",
        "bluecoat",
        "data-source",
        "download",
        "cpu-monitor",
        "event-log",
        "level",
        "syslog en",
        "syslog fa",
        "smtp",
        "http",
        "remove",
        "management-services",
        "force-bypass",
        "proxy-services",
        "delete",
        "attribute",
        "alert",
        "im http",
        "ntp clear",
        "restart",
        "snmp",
        "authentication",
        "privacy",
        "tcp-ip",
        "policy hmac",
        "upgrade-path",
        "default",
        "license-key",
        "statistics-export",
        "ssl-device-profile",
        "(",
        "<",
        "$",
        ")",
        "Click",
        "if",
        "{",
        "}",
        "document.",
        "//",
        "function",
        "var",
        "pin.",
        "return",
        "cookie",
        "else",
        "challenge",
        "realm",
        "rsacompare",
        "isrsarealm",
        "beginlocation",
        "define",
        "end",
        "name=",
        "single=",
        "type=",
        "n=",
        "d=",
        "h=",
        "f-o=",
        "port=",
        "n-",
        "cmt=",
        "t=",
        "typ=",
        "delimiters=",
        "group-",
        "restrict=",
        "suffix=",
        "layertype=",
        "id=",
        "col=",
        "negate=",
        "disabled=",
        "num=",
        "&lt",
        "hashed-",
        'group add "readonly"',
        "line-vty",
    ),
    "f5": (
        "#",
        "cli",
        "update",
        "apm",
        "report",
        "user",
        "auth",
        "role-",
        "/",
        "console",
        "line",
        "role",
        "default-",
        "fallback",
        "type",
        "account",
        "protocol",
        "secret",
        "service",
        "encrypted-p",
        "partition",
        "all-",
        "session-",
        "shell",
        "alias-",
        "prompt",
        "suppress-",
        "cm",
        "cache-",
        "cert",
        "--",
        "checksum",
        "revision",
        "active-mo",
        "build",
        "edition",
        "key",
        "marketing-name",
        "multicast-interface",
        "multicast-port",
        "optional-",
        "product",
        "platform-id",
        "self-device",
        "time-",
        "unicast-address",
        "effective-ip management-ip",
        "effective-port",
        "ip management-ip",
        "multicast-ip",
        "hidden",
        "network-failover",
        "unit-id",
        "ca-",
        "status",
        "trust-group",
        "gtm",
        "ilx global-settings",
        "addresses none",
        "debug-port-blacklist",
        "rule none",
        "members",
        "load-balancing-mode",
        "ip-protocol tcp",
        "profiles",
        "mask",
        "rules",
        "source 0.0.0.0/0",
        "source-address-",
        "translate-port",
        "translate-address enabled",
        "creation-time",
        "last-modified-time",
        "persist",
        "default yes",
        "arp",
        "icmp-echo",
        "adaptive",
        "defaults-from",
        "destination *.",
        "interval",
        "ip-dscp",
        "recv",
        "send",
        "time-until-up",
        "timeout",
        "app-service",
        "net port-list",
        "id",
        "vlan",
        "net self-allow",
        "defaults",
        "igmp",
        "ospf",
        "pim",
        "tcp",
        "udp",
        "interfaces",
        "trunks",
        "net stp",
        "net trunk HA",
        "lacp ",
        "tag",
        "net fdb",
        "net ipsec",
        "pem ",
        "security device",
        "id ",
        "action",
        "ip-protocol",
        "sys",
        "inherited-",
        "gui-",
        "request-options",
        "bfd-",
        "flooding-type",
        "log-level",
        "logical-",
        "tunnel-maintenance-mode",
        "network default",
        "level nominal",
        "agent-addresses",
        "communities",
        "disk-monitors",
        "minspace",
        "max-processes",
        "process",
        "snmpv",
        "privacy-",
        "version",
        "expiration",
        "options",
        "password",
        "development-mode",
        "property-",
        "availability-",
        "valid-values",
        "instance-type",
        "region",
        "dhcp-",
        "node-",
        "cloud-",
        "auto-",
        "end-",
        "frequency",
        "wom",
    ),
    "aruba": (
        "interface",
        "switchport",
        "spanning",
        "key",
        "netservice",
        "priority-map",
        "queue-weights",
        "ap-console-password",
        "bkup-passwords",
        "g-",
        "a-",
        "wmm",
        "qbss-",
        '"',
        "band-",
        "regulatory-domain",
        'id "',
        "airgroupprofile",
        "logging level",
        "logging security",
        "snmp-server trap",
        "conductor-l3redundancy",
        "l3-sync",
        "ip nat",
        "permit any",
        "netservice svc-",
        "netdestination6 ipv6-reserved-range",
        "invert",
        "netexthdr",
        "time-range",
        "weekday",
        "user",
        "any any svc-",
        "ipv6 any any",
        "network 127.",
        "network 169.254.",
        "network 224.0.0",
        "host 255.255.255.255",
        "network 240.0.0.0",
        "any any any permit",
        "ipv6 host fe80",
        "ipv6 network fc00",
        "ipv6 network fe80",
        "ipv6 alias ipv6-reserved-range",
        "ipv6 any any any",
        "any any app alg-",
        "ipv6 any any svc-",
        "ipv6 any any svc-v6-dhcp permit",
        "ip access-list session captiveportal",
        "any any tcp",
        "any any udp",
        "any any ip",
        "no ",
        "vpn-dialer",
        "ike authentication",
        "aaa tacacs",
        "command ",
        "controller-ip vlan",
        "datapath",
        "kernel coredump",
        "interface mgmt",
        "shutdown",
        "vlan ",
        "trusted",
        "ip nexthop",
        "crypto ",
        "version",
        "encryption",
        "hash",
        "authentication",
        "group",
        "prf",
        "set transform-set",
        "localip 0.0.0.0 ipsec",
        "vpdn",
        "ip dynamic-dns",
        "snmp-server",
        "tunneled-node-address",
        "adp",
        "ap",
        "amon",
        "ssh mgmt-",
        "mgmt-user ",
        "ip mobile",
        "ip igmp",
        "ipv6 mld",
        "firewall",
        "prohibit-ip-spoofing",
        "attack-rate",
        "session-idle-timeout",
        "cp-",
        "amsdu",
        "wireless-",
        "session-tunnel-fib",
        "optimize-dad-frames",
        "deny-needfrag-df-ipsec",
        "ipv6 firewall",
        "ext-hdr-parse-len",
        "dpi-classif-cache",
        "ipv4 permit any proto 6",
        "ipv6 permit any proto 6",
        "ipv6 deny any proto",
        "ip domain",
        "country",
        "change-config-node",
        "key ",
        "session-authorization",
        "aaa authentication via",
        "scheduler-profile",
        "authentication-mac",
        "mac-default-role",
        "initial-role",
        "enable",
        "web-",
        "guest-",
        "ids",
        "control-plane-security",
        "aaa policy",
        "valid-network",
        "traceoptions",
        "activate",
        "file ",
        "ucc",
        "license-",
        "pefng-",
        "rfp-",
        "papi-security",
        "est profile",
        "aruba-central",
        "ifmap cppm",
        "pan",
        "banner",
        "virtual-ap",
        "websocket",
        "openflow",
        "sdwan-profile",
        "valid-",
        "gps",
        "channel-",
        "node-",
        "frame-type",
        "dst-mac",
        "src-mac",
        "bssid valid-ap",
        "payload",
        "rf",
        "arm-",
        "wlan hotspot",
        "wpa-passphrase",
        "opmode",
        "mcast-rate-opt",
        "band-steering",
        "dynamic-mcast-optimization",
        "broadcast-filter",
        "stats-enable",
        "tag-enable",
        "sessions-enable",
        "monitored-",
        "wids-",
        "misc-",
        "location-e",
        "uccmonitoring-",
        "airgroupinfo-",
        "wan-state",
        "airmatch",
        "condition",
        "enet",
        'service "',
        "process",
        "ale-configuration",
    ),
    "cisco": (
        "!",
        "*",
        "^C",
        "#",
        "end",
        "Building",
        "timers",
        "ip bgp-community new-format",
        "route-map bgp_to_ospf",
        "Current",
        "boot",
        "vrf definition mgmtVrf",
        "address-family ",
        "exit-address-family",
        "mac-address ",
        "rd ",
        "route-target ",
        "ip multicast",
        "service-policy",
        "power redundancy",
        "mac access-list",
        "redundancy",
        "mode",
        "lldp",
        "priority",
        "police",
        "dbl",
        "speed ",
        "duplex ",
        "dual-active",
        "ip vrf forwarding",
        "ip ospf authentication",
        "ip ospf message-digest-key",
        "passive-interface",
        "logging buffered",
        "logging monitor",
        "logging trap",
        "logging origin",
        "logging source",
        "username",
        "redistribute",
        "bgp log",
        "permit tcp any any",
        "permit udp any any",
        "deny ipv6 any any",
        "permit ipv6 any any",
        "permit ip any any",
        "permit udp any eq boot",
        "ipv6 access-list IPv6-Deny-All",
        "ip access-list extended AutoQos",
        "ip access-list extended VSL-",
        "ipv6 access-list VSL-",
        "stopbits",
        "track ",
        "permit ip any 224",
        "vrf",
        "threshold",
        "timeout",
        "frequency",
        "limit-resource",
        "feature",
        "hardware",
        "copp",
        "bfd",
        "rmon event",
        "rd auto",
        "route-target",
        "vpc domain",
        "host-reachability",
        "vpc peer-link",
        "nve1",
        "ip forward",
        "advertise virtual-rmac",
        "medium p2p",
        "ip router ospf",
        "port-type",
        "icam ",
        "boot ",
        "log-neighbor-changes",
        "update-source",
        "nv overlay",
        "tacacs-server",
        # Shell specific
        "access-list 1 ",
        "access-list 16 ",
        "access-list 22 ",
        "route-map STATIC-TO-OSPF",
        "permit ipv6 any FF02::/124",
        "module provision",
        "chassis-type",
        "mac address-table",
        "ntp source",
        "clock",
        "switch ",
        "vtp m",
        "mls qos",
        "subject-",
        "priority-queue",
        "version",
        "service",
        "platform",
        "interface",
        "switchport",
        "spanning",
        "aaa",
        "option",
        "flow",
        "crypto pki",
        "certificate",
        "negoti",
        "cdp",
        "encapsu",
        "bandwi",
        "ip pim",
        "no ",
        "auto-cost",
        "snmp-server enable traps",
        "banner",
        "line",
        "transport",
        "access-cl",
        "ipv6 access-class",
        "exec-timeout",
        "session-timeout",
        "call-home",
        "contact-email-addr",
        'profile "Cisco',
        "escape-",
        "mab",
        "dot1x",
        "authentication",
        "shutdown",
        "ip http",
        "ip ssh",
        "ip ftp",
        "ip tf",
        "iox",
        "ip tacacs",
        "snmp",
        "ip radi",
        "server-private",
        "client ",
        "udld",
        "table",
        "ip dhcp",
        "login",
        "enrollment",
        "revocation",
        "rsakeypair",
        "license",
        "errdisable",
        "memory",
        "match",
        "policy-map",
        "class",
        "queue-",
        "set ",
        "auto",
        "vlan",
        "ip ospf network",
        "ip mtu",
        "channel-group",
        # "ip helper-address ",
        "router ospf",
        "capability",
        "remark",
        "ip sla",
        "slot",
        "load-interval",
        "stackwise-virtual",
        "domain ",
        "ip vrf ",
        "default copy",
        "quit",
        "cabundle ",
        "diagnostic ",
        "transceiver",
        "monitoring",
        "ip access-list standard network_management",
        "control-plane",
        "active",
        "restconf",
        "destination transport-method",
        "area ",
        "radius server",
        "key 7 ",
        "standby 1 preempt",
        "ip flow",
        "downshift",
        "alarm ",
        "syslog ",
        "notifies ",
        "map ",
        "ptp ",
        "auth-type",
        "system mtu",
        "ip routing",
        "deadtime",
        "port",
        "random-detect ",
        "shape ",
        "exceed-",
        "conform-",
        "multilink",
        "subscriber",
        "config rogue",
        "config qos",
        "config license",
        "config logging syslog level",
        "config snmp v3user",
        "config media-stream",
        "config advanced",
        "config radius",
        "config mgmtuser",
        "config rf-profile",
        "config custom-web",
        "config flexconnect",
        "config acl rule source port",
        "config acl rule destination port",
        "config acl rule add",
        "config acl rule proto",
        "config acl rule dir",
        "config spann",
        "config wlan aaa-",
        "config wlan mfp",
        "config wlan broadcast",
        "config wlan create",
        "config wlan band-",
        "config wlan exclusionlist",
        "config wlan dms",
        "config wlan qos",
        "config wlan security",
        "config wlan interface",
        "config wlan media-stream",
        "config wlan session-",
        "config wlan nac",
        "config wlan mac-filtering",
        "config aaa",
        "config wps",
        "config rfid",
        "config 802.11",
        "config tacacs",
        "config trapflags",
        "config ap",
        "config mdns",
        "config location",
        "config interface vlan",
        # "config interface dhcp",
        "config interface create",
        "config database",
        "config network secureweb",
        "config network webmode",
        "config network ssh",
        "config network usertimeout",
        "config network arptimeout",
        "config network multicast",
        "config switchconfig",
        "config ipv6 disable",
        "config macfilter",
        "config lag enable",
        "config certificate generate",
        "config logging buffered",
        "config nmsp",
        "config wlan radius_server",
        "config 802.11b",
        "transfer ",
        "config wlan wmm",
        "config wlan enable",
        "config wlan apgroup wlan-radio-policy",
        "config wlan apgroup hyperlocation",
        "config wlan apgroup qinq",
        "config wlan apgroup interface-mapping",
    ),
    "paloalto": (
        "set shared certificate",
        "set panorama certificate",
        "set deviceconfig system service",
        "set deviceconfig system update",
        "set deviceconfig system log-",
        "set deviceconfig system speed-",
        "set deviceconfig system timezone",
        "set deviceconfig system eth1 service",
        "set deviceconfig system eth1 speed-",
        "set deviceconfig system type",
        "set deviceconfig system snmp-setting",
        "set deviceconfig system device-telemetry",
        "set deviceconfig setting management",
        "set mgt-config users",
        "set mgt-config password",
        "set panorama log-settings traffic",
        "set network ike",
        "set network qos",
        "set network tunnel",
        "set shared",
        "set rulebase",
        "set zone",
        "set application",
        "set service",
        "set schedule"
    )
}

standard_keywords: Dict[str, Tuple[str, ...]] = {
    "paloalto": (
        "set",
        "protocol",
        "shared",
        "botnet",
        "configuration",
        "qos",
        "profile",
        "default",
        "ike",
        "gateway",
        "application",
        "service",
        "application-group",
        "service-group",
        "rulebase",
        "zone",
        "mgt-config",
        "users",
        "password-complexity",
        "default-security-rules",
        "crypto-profiles",
        "profiles",
        "interface",
        "ethernet",
        "deviceconfig",
        "system",
    ),
    "aruba": (
        "aaa",
        "authentication",
        "auth",
        "position",
        "jitter",
        "frequency",
        "vpnc",
        "data",
        "dot11g",
        "dot11a",
        "bcast",
        "hide",
        "eirp",
        "20mhz",
        "dot11h",
        "160mhz",
        "url",
        "php",
        "page",
        "pause",
        "redirect",
        "ipv4",
        "ipv6",
        "dpi",
        "conductor",
        "factory",
        "dst",
        "src",
        "ipsecmap10",
        "map",
        "source",
        "guestcppm",
        "30mb",
        "roleui",
        "10mbdownstreamper",
        "mbits",
        "chi",
        "minh",
        "ho",
    ),
    "cisco": (
        "ip",
        "config",
        "acl",
        "action",
        "address",
        "network",
        "id",
        "area",
        "access",
        "list",
        "eq",
        "udp",
        "tcp",
        "range",
        "host",
        "any",
        "remark",
        "permit",
        "gt",
        "lt",
        "fragments",
        "position",
        "standard",
        "setmedprimary",
        "crashinfo",
        "mls",
        "interval",
        "setcommunity",
        "ffff",
        "ffe",
        "buffersize",
        "table",
        "null",
        "software",
        "upgrade",
        "auto",
        "docker",
        "hosting",
        "pkg",
        "start",
        "extended",
        "log",
        "gigabitethernet",
        "overload",
        "hmac",
        "vti",
        "ikev",
        "cbc",
        "sha",
        "inside",
        "outside",
        "cssm",
        "sampler",
        "keys",
        "mgcp",
        "none",
        "force",
        "model",
        "prefer",
        "ftp",
        "ssh",
        "tftp",
        "http",
        "tacacs",
        "ntp",
        "destination",
        "tunnel",
        "source",
        "snmp",
        "bfd",
        "eigrp",
        "ospf",
        "router",
        "loopback",
        "wan",
        "routing",
        "for",
        "snmptrap",
        "bootpc",
        "bootps",
        "single",
        "deny",
        "and",
        "or",
        "not",
        "if",
        "logging",
        "route",
        "static",
        "port",
        "ports",
        "netbios",
        "the",
        "to",
        "gre",
        "interface",
        "vlan",
        "isakmp",
        "crypto",
        "keyring",
        "all",
        "protocol",
        "ldap",
        "citrix",
        "keepalives",
        "dscp",
        "shell",
        "trap",
        "domain",
        "traffic",
        "queue",
        "sequence",
        "ipv6",
        "loopbacks",
        "mgmnt",
        "icmp",
        "audio",
        "video",
        "catchall",
        "voice",
        "classify",
        "catch",
        "acct",
        "auth",
        "ipv4",
        "vtp",
        "mode",
        "z1",
        "zc",
        "default",
        "gateway",
        "line",
        "vty",
        "nhs",
        "nbma",
        "shortcut",
        "user",
        "printer",
        "hold",
        "hostname:",
        "location:",
        "echo",
        "vrf",
        "office",
        "client",
        "md",
        "management",
        "cost",
        "6to4",
        "addresses",
        "site",
        "local",
        "multicast",
        "packets",
        "transport",
        "every",
        "subnet",
        "everything",
        "it",
        "else",
        "routing-type",
        "mobile-ipv6",
        "undetermined",
        "preference",
        "less",
        "from",
        "allow",
        "lan",
        "owner",
        "sdwan",
        "filter",
        "jitter",
        "community",
        "distance",
        "reflector",
        "setmedsecondary",
        "denycommunity",
        "both",
        "summary",
        "only",
        "aggregate",
        "ebgp",
        "multihop",
        "tag",
        "suppress",
        "nd",
        "ra",
        "enable",
        "original",
        "input",
        "netflow",
        "ratio",
        "of",
        "record",
        "entries",
        "active",
        "cache",
        "timeout",
        "collector",
        "exporter",
        "unicast",
        "expiry",
        "time",
        "watch",
        "admission",
        "unreachable",
        "traceroute",
        "exceeded",
        "data",
        "established",
        "packet",
        "too",
        "big",
        "administratively",
        "prohibited",
        "esp",
        "www",
        "block",
        "routes",
        "an",
        "originate",
        "activate",
        "next",
        "hop",
        "self",
        "path",
        "update",
        "timers",
        "peer",
        "group",
        "listen",
        "dhcp",
        "dns",
        "lookup",
        "key",
        "multipoint",
        "protection",
        "forced",
        "redirect",
        "holdtime",
        "authentication",
        "nhrp",
        "aes",
        "transform",
        "set",
        "idle",
        "seconds",
        "security",
        "association",
        "ipsec",
        "invalid",
        "spi",
        "recovery",
        "mtu",
        "fragmentation",
        "dial",
        "limit",
        "periodic",
        "dpd",
        "identity",
        "lifetime",
        "profile",
        "pre",
        "shared",
        "integrity",
        "proposal",
        "encryption",
        "clock",
        "synchronization",
        "automatic",
        "exit",
        "seq",
        "le",
        "inboud",
        "outbound",
        "pim",
        "no",
        "with",
        "new",
        "format",
        "null0",
        "mask",
        # 'neighbor',
        "in",
        "out",
        "send",
        "soft",
        "reconfiguration",
        "prefix",
        "media",
        "type",
        "verify",
        "reverse" "path",
        "decrement",
        "increment",
        "priority",
        "track",
        "standby",
        "policy",
        "map",
        "keepalive",
        "adjust",
        "mss",
        "up",
        "down",
        "delay",
        "description",
        "ewlc",
        "control",
        "topology",
        "forwarding",
        "lvx",
        "transit",
        "inter",
        "fed",
        "openflow",
        "exception",
        "egr",
        "nfl",
        "sampled",
        "rpf",
        "failed",
        "punt",
        "webauth",
        "forus",
        "resolution",
        "end",
        "station",
        "high",
        "rate",
        "applications",
        "mcast",
        "dot",
        "gen",
        "broadcast",
        "stackwise",
        "virtual",
        "oob",
        "low",
        "latency",
        "snooping",
        "system",
        "critical",
        "gold",
        "pkt",
        "icmpgen",
        "l2lvxcntrl",
        "protosnoop",
        "puntwebauth",
        "mcastdata",
        "xauth",
        "swfwd",
        "lvxdata",
        "forustraffic",
        "forusarp",
        "mcastendstn",
        "egrexcption",
        "nflsampled",
        "rpffailed",
        "twe",
        "eth",
        "channel",
        "systems",
        "ipv",
    ),
}
